const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const TOGGLE_NAV_MODAL = "TOGGLE_NAV_MODAL";
const CLOSE_NAV_MODAL = "CLOSE_NAV_MODAL";
const BEGIN_REGISTER = "BEGIN_REGISTER";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_ERROR = "REGISTER_SUCCESS";
const BEGIN_LOGIN = "BEGIN_LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_SUCCESS";
const LOGOUT_USER = "LOGOUT_USER";
const BEGIN_UPDATE = "BEGIN_UPDATE";
const UPDATE_SUCCESS = "UPDATE_SUCCESS";
const UPDATE_ERROR = "UPDATE_SUCCESS";

export {
  CLOSE_SIDEBAR,
  OPEN_SIDEBAR,
  TOGGLE_NAV_MODAL,
  CLOSE_NAV_MODAL,
  BEGIN_REGISTER,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
  BEGIN_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT_USER,
  BEGIN_UPDATE,
  UPDATE_SUCCESS,
  UPDATE_ERROR,
};
